# Generated by Django 5.2 on 2025-10-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financetracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
